from pathlib import Path
from tempfile import NamedTemporaryFile

from fastapi import (
    APIRouter,
    Depends,
    File,
    Query,
    UploadFile,
    HTTPException,
)

from sqlalchemy.orm import Session

from app.database import get_db
from app.models.reservoir import Reservoir
from app.services.cwc_reservoirs import (
    ingest_cwc_pdf,
)


DEFAULT_RESERVOIRS = [   {   'basin': 'Krishna Basin',
        'cap': 8.9,
        'cca': 190000.0,
        'district': 'Nandyal',
        'frl': 269.75,
        'last_pct': 84.5,
        'lat': 16.0864,
        'level': 268.45,
        'lon': 78.8986,
        'mw': 1670.0,
        'name': 'Srisailam Dam',
        'norm_pct': 75.0,
        'pct': 92.6,
        'region': 'Southern',
        'state': 'Andhra Pradesh',
        'storage': 8.24,
        'warn': True},
    {   'basin': 'Krishna Basin',
        'cap': 9.37,
        'cca': 895000.0,
        'district': 'Palnadu',
        'frl': 179.83,
        'last_pct': 78.2,
        'lat': 16.5772,
        'level': 178.1,
        'lon': 79.3138,
        'mw': 816.0,
        'name': 'Nagarjuna Sagar',
        'norm_pct': 72.0,
        'pct': 88.8,
        'region': 'Southern',
        'state': 'Andhra Pradesh',
        'storage': 8.32,
        'warn': True},
    {   'basin': 'Godavari Basin',
        'cap': 5.51,
        'cca': 291000.0,
        'district': 'Eluru',
        'frl': 45.72,
        'last_pct': 65.0,
        'lat': 17.2562,
        'level': 35.8,
        'lon': 81.6568,
        'mw': 960.0,
        'name': 'Polavaram Project',
        'norm_pct': 68.0,
        'pct': 71.7,
        'region': 'Southern',
        'state': 'Andhra Pradesh',
        'storage': 3.95,
        'warn': False},
    {   'basin': 'Krishna Basin',
        'cap': 0.08,
        'cca': 526000.0,
        'district': 'Krishna',
        'frl': 17.37,
        'last_pct': 95.0,
        'lat': 16.5075,
        'level': 17.37,
        'lon': 80.6053,
        'mw': 0.0,
        'name': 'Prakasam Barrage',
        'norm_pct': 90.0,
        'pct': 100.0,
        'region': 'Southern',
        'state': 'Andhra Pradesh',
        'storage': 0.08,
        'warn': True},
    {   'basin': 'Godavari Basin',
        'cap': 0.09,
        'cca': 400000.0,
        'district': 'East Godavari',
        'frl': 13.9,
        'last_pct': 85.0,
        'lat': 16.9388,
        'level': 13.8,
        'lon': 81.7686,
        'mw': 0.0,
        'name': 'Dowleswaram Barrage',
        'norm_pct': 80.0,
        'pct': 88.9,
        'region': 'Southern',
        'state': 'Andhra Pradesh',
        'storage': 0.08,
        'warn': True},
    {   'basin': 'Pennar Basin',
        'cap': 2.21,
        'cca': 182000.0,
        'district': 'Nellore',
        'frl': 100.58,
        'last_pct': 72.0,
        'lat': 14.5028,
        'level': 96.2,
        'lon': 79.3039,
        'mw': 0.0,
        'name': 'Somasila Dam',
        'norm_pct': 68.0,
        'pct': 80.5,
        'region': 'Southern',
        'state': 'Andhra Pradesh',
        'storage': 1.78,
        'warn': False},
    {   'basin': 'Pennar Basin',
        'cap': 1.93,
        'cca': 120000.0,
        'district': 'Tirupati',
        'frl': 84.73,
        'last_pct': 68.5,
        'lat': 14.3333,
        'level': 79.4,
        'lon': 79.6167,
        'mw': 0.0,
        'name': 'Kandaleru Dam',
        'norm_pct': 65.0,
        'pct': 75.1,
        'region': 'Southern',
        'state': 'Andhra Pradesh',
        'storage': 1.45,
        'warn': False},
    {   'basin': 'Gosthani Basin',
        'cap': 0.09,
        'cca': 62000.0,
        'district': 'Vizianagaram',
        'frl': 89.0,
        'last_pct': 70.0,
        'lat': 18.17,
        'level': 86.5,
        'lon': 83.2,
        'mw': 0.0,
        'name': 'Tatipudi Reservoir',
        'norm_pct': 72.0,
        'pct': 77.8,
        'region': 'Southern',
        'state': 'Andhra Pradesh',
        'storage': 0.07,
        'warn': False},
    {   'basin': 'Yeleru Basin',
        'cap': 0.51,
        'cca': 85000.0,
        'district': 'Kakinada',
        'frl': 86.56,
        'last_pct': 71.0,
        'lat': 17.3333,
        'level': 82.1,
        'lon': 82.0833,
        'mw': 0.0,
        'name': 'Yeleru Reservoir',
        'norm_pct': 69.0,
        'pct': 76.5,
        'region': 'Southern',
        'state': 'Andhra Pradesh',
        'storage': 0.39,
        'warn': False},
    {   'basin': 'Godavari Basin',
        'cap': 0.46,
        'cca': 750000.0,
        'district': 'Jayashankar Bhupalpally',
        'frl': 100.0,
        'last_pct': 75.0,
        'lat': 18.7067,
        'level': 94.5,
        'lon': 79.9144,
        'mw': 0.0,
        'name': 'Kaleshwaram (Medigadda) Barrage',
        'norm_pct': 70.0,
        'pct': 82.6,
        'region': 'Southern',
        'state': 'Telangana',
        'storage': 0.38,
        'warn': False},
    {   'basin': 'Godavari Basin',
        'cap': 2.56,
        'cca': 392000.0,
        'district': 'Nizamabad',
        'frl': 332.54,
        'last_pct': 79.0,
        'lat': 18.9667,
        'level': 330.1,
        'lon': 78.3333,
        'mw': 36.0,
        'name': 'Sri Rama Sagar (Pochampad)',
        'norm_pct': 74.0,
        'pct': 89.1,
        'region': 'Southern',
        'state': 'Telangana',
        'storage': 2.28,
        'warn': True},
    {   'basin': 'Godavari Basin',
        'cap': 0.21,
        'cca': 27000.0,
        'district': 'Nirmal',
        'frl': 213.36,
        'last_pct': 82.0,
        'lat': 19.1,
        'level': 211.8,
        'lon': 78.7833,
        'mw': 0.0,
        'name': 'Kaddam Dam',
        'norm_pct': 75.0,
        'pct': 90.5,
        'region': 'Southern',
        'state': 'Telangana',
        'storage': 0.19,
        'warn': True},
    {   'basin': 'Manjira Basin',
        'cap': 0.5,
        'cca': 93000.0,
        'district': 'Kamareddy',
        'frl': 428.24,
        'last_pct': 71.5,
        'lat': 18.1667,
        'level': 425.6,
        'lon': 77.9667,
        'mw': 10.0,
        'name': 'Nizam Sagar',
        'norm_pct': 68.0,
        'pct': 78.0,
        'region': 'Southern',
        'state': 'Telangana',
        'storage': 0.39,
        'warn': False},
    {   'basin': 'Manjira Basin',
        'cap': 0.85,
        'cca': 16000.0,
        'district': 'Sangareddy',
        'frl': 523.6,
        'last_pct': 74.0,
        'lat': 17.75,
        'level': 521.1,
        'lon': 77.9333,
        'mw': 15.0,
        'name': 'Singur Dam',
        'norm_pct': 70.0,
        'pct': 83.5,
        'region': 'Southern',
        'state': 'Telangana',
        'storage': 0.71,
        'warn': False},
    {   'basin': 'Manair Basin',
        'cap': 0.68,
        'cca': 156000.0,
        'district': 'Karimnagar',
        'frl': 280.42,
        'last_pct': 76.0,
        'lat': 18.4,
        'level': 277.9,
        'lon': 79.1333,
        'mw': 0.0,
        'name': 'Lower Manair Dam',
        'norm_pct': 72.0,
        'pct': 85.3,
        'region': 'Southern',
        'state': 'Telangana',
        'storage': 0.58,
        'warn': True},
    {   'basin': 'Manair Basin',
        'cap': 0.73,
        'cca': 81000.0,
        'district': 'Rajanna Sircilla',
        'frl': 318.0,
        'last_pct': 70.0,
        'lat': 18.3833,
        'level': 314.5,
        'lon': 78.9667,
        'mw': 0.0,
        'name': 'Mid Manair Dam',
        'norm_pct': 68.0,
        'pct': 79.5,
        'region': 'Southern',
        'state': 'Telangana',
        'storage': 0.58,
        'warn': False},
    {   'basin': 'Krishna Basin',
        'cap': 0.33,
        'cca': 41000.0,
        'district': 'Jogulamba Gadwal',
        'frl': 318.52,
        'last_pct': 85.0,
        'lat': 16.3333,
        'level': 317.9,
        'lon': 77.7,
        'mw': 234.0,
        'name': 'Jurala Dam (Priyadarshini)',
        'norm_pct': 80.0,
        'pct': 93.9,
        'region': 'Southern',
        'state': 'Telangana',
        'storage': 0.31,
        'warn': True},
    {   'basin': 'Krishna Basin',
        'cap': 3.12,
        'cca': 362000.0,
        'district': 'Vijayanagara',
        'frl': 497.74,
        'last_pct': 81.0,
        'lat': 15.263,
        'level': 495.2,
        'lon': 76.337,
        'mw': 127.0,
        'name': 'Tungabhadra Dam',
        'norm_pct': 76.0,
        'pct': 90.1,
        'region': 'Southern',
        'state': 'Karnataka',
        'storage': 2.81,
        'warn': True},
    {   'basin': 'Cauvery Basin',
        'cap': 1.4,
        'cca': 77000.0,
        'district': 'Mandya',
        'frl': 38.04,
        'last_pct': 86.0,
        'lat': 12.4411,
        'level': 37.5,
        'lon': 76.5722,
        'mw': 0.0,
        'name': 'KRS (Krishna Raja Sagara)',
        'norm_pct': 80.0,
        'pct': 95.7,
        'region': 'Southern',
        'state': 'Karnataka',
        'storage': 1.34,
        'warn': True},
    {   'basin': 'Krishna Basin',
        'cap': 3.44,
        'cca': 622000.0,
        'district': 'Vijayapura',
        'frl': 519.6,
        'last_pct': 85.2,
        'lat': 16.3267,
        'level': 518.3,
        'lon': 75.8872,
        'mw': 290.0,
        'name': 'Almatti Dam (Lal Bahadur Shastri)',
        'norm_pct': 79.0,
        'pct': 93.6,
        'region': 'Southern',
        'state': 'Karnataka',
        'storage': 3.22,
        'warn': True},
    {   'basin': 'Krishna Basin',
        'cap': 1.07,
        'cca': 420000.0,
        'district': 'Yadgir',
        'frl': 492.25,
        'last_pct': 84.0,
        'lat': 16.3167,
        'level': 490.8,
        'lon': 76.5833,
        'mw': 0.0,
        'name': 'Narayanpur Dam (Basava Sagara)',
        'norm_pct': 80.0,
        'pct': 91.6,
        'region': 'Southern',
        'state': 'Karnataka',
        'storage': 0.98,
        'warn': True},
    {   'basin': 'Sharavathi Basin',
        'cap': 4.37,
        'cca': 0.0,
        'district': 'Shivamogga',
        'frl': 554.43,
        'last_pct': 82.0,
        'lat': 14.2333,
        'level': 551.2,
        'lon': 74.8333,
        'mw': 1035.0,
        'name': 'Linganamakki Dam',
        'norm_pct': 78.0,
        'pct': 89.0,
        'region': 'Southern',
        'state': 'Karnataka',
        'storage': 3.89,
        'warn': True},
    {   'basin': 'Krishna Basin',
        'cap': 2.03,
        'cca': 105000.0,
        'district': 'Chikkamagaluru',
        'frl': 657.76,
        'last_pct': 79.0,
        'lat': 13.7,
        'level': 654.5,
        'lon': 75.6333,
        'mw': 39.2,
        'name': 'Bhadra Dam',
        'norm_pct': 75.0,
        'pct': 88.2,
        'region': 'Southern',
        'state': 'Karnataka',
        'storage': 1.79,
        'warn': True},
    {   'basin': 'Cauvery Basin',
        'cap': 0.55,
        'cca': 62000.0,
        'district': 'Mysuru',
        'frl': 696.16,
        'last_pct': 88.0,
        'lat': 11.9667,
        'level': 694.9,
        'lon': 76.35,
        'mw': 0.0,
        'name': 'Kabini Reservoir',
        'norm_pct': 82.0,
        'pct': 94.5,
        'region': 'Southern',
        'state': 'Karnataka',
        'storage': 0.52,
        'warn': True},
    {   'basin': 'Cauvery Basin',
        'cap': 0.24,
        'cca': 54000.0,
        'district': 'Kodagu',
        'frl': 871.42,
        'last_pct': 85.0,
        'lat': 12.4833,
        'level': 870.2,
        'lon': 75.9,
        'mw': 9.0,
        'name': 'Harangi Dam',
        'norm_pct': 80.0,
        'pct': 91.7,
        'region': 'Southern',
        'state': 'Karnataka',
        'storage': 0.22,
        'warn': True},
    {   'basin': 'Cauvery Basin',
        'cap': 1.05,
        'cca': 265000.0,
        'district': 'Hassan',
        'frl': 890.58,
        'last_pct': 80.0,
        'lat': 12.9167,
        'level': 888.1,
        'lon': 76.05,
        'mw': 0.0,
        'name': 'Hemavathi Dam (Gorur)',
        'norm_pct': 77.0,
        'pct': 89.5,
        'region': 'Southern',
        'state': 'Karnataka',
        'storage': 0.94,
        'warn': True},
    {   'basin': 'Krishna Basin',
        'cap': 1.07,
        'cca': 218000.0,
        'district': 'Belagavi',
        'frl': 633.83,
        'last_pct': 75.0,
        'lat': 15.8167,
        'level': 631.1,
        'lon': 75.1167,
        'mw': 0.0,
        'name': 'Malaprabha Dam (Renuka Sagara)',
        'norm_pct': 72.0,
        'pct': 83.2,
        'region': 'Southern',
        'state': 'Karnataka',
        'storage': 0.89,
        'warn': False},
    {   'basin': 'Krishna Basin',
        'cap': 1.45,
        'cca': 298000.0,
        'district': 'Belagavi',
        'frl': 662.94,
        'last_pct': 78.0,
        'lat': 16.15,
        'level': 660.4,
        'lon': 74.6333,
        'mw': 32.0,
        'name': 'Ghataprabha Dam (Hidkal)',
        'norm_pct': 75.0,
        'pct': 86.2,
        'region': 'Southern',
        'state': 'Karnataka',
        'storage': 1.25,
        'warn': True},
    {   'basin': 'Cauvery Basin',
        'cap': 2.64,
        'cca': 660000.0,
        'district': 'Salem',
        'frl': 36.58,
        'last_pct': 74.0,
        'lat': 11.8,
        'level': 35.1,
        'lon': 77.8,
        'mw': 240.0,
        'name': 'Mettur Dam (Stanley Reservoir)',
        'norm_pct': 68.0,
        'pct': 85.2,
        'region': 'Southern',
        'state': 'Tamil Nadu',
        'storage': 2.25,
        'warn': True},
    {   'basin': 'Bhavani Basin',
        'cap': 0.93,
        'cca': 84000.0,
        'district': 'Erode',
        'frl': 27.74,
        'last_pct': 75.0,
        'lat': 11.4667,
        'level': 25.8,
        'lon': 77.1167,
        'mw': 32.0,
        'name': 'Bhavanisagar Dam',
        'norm_pct': 70.0,
        'pct': 83.9,
        'region': 'Southern',
        'state': 'Tamil Nadu',
        'storage': 0.78,
        'warn': False},
    {   'basin': 'Vaigai Basin',
        'cap': 0.19,
        'cca': 55000.0,
        'district': 'Theni',
        'frl': 21.64,
        'last_pct': 73.0,
        'lat': 10.05,
        'level': 19.8,
        'lon': 77.5833,
        'mw': 6.0,
        'name': 'Vaigai Dam',
        'norm_pct': 69.0,
        'pct': 84.2,
        'region': 'Southern',
        'state': 'Tamil Nadu',
        'storage': 0.16,
        'warn': False},
    {   'basin': 'Bharathappuzha Basin',
        'cap': 0.11,
        'cca': 17000.0,
        'district': 'Coimbatore',
        'frl': 365.76,
        'last_pct': 75.0,
        'lat': 10.4833,
        'level': 362.4,
        'lon': 76.9667,
        'mw': 60.0,
        'name': 'Aliyar Dam',
        'norm_pct': 70.0,
        'pct': 81.8,
        'region': 'Southern',
        'state': 'Tamil Nadu',
        'storage': 0.09,
        'warn': False},
    {   'basin': 'Chalakkudy Basin',
        'cap': 0.15,
        'cca': 0.0,
        'district': 'Coimbatore',
        'frl': 1002.79,
        'last_pct': 79.0,
        'lat': 10.3,
        'level': 998.5,
        'lon': 76.8833,
        'mw': 95.0,
        'name': 'Sholayar Dam',
        'norm_pct': 76.0,
        'pct': 86.7,
        'region': 'Southern',
        'state': 'Tamil Nadu',
        'storage': 0.13,
        'warn': True},
    {   'basin': 'Amaravathi Basin',
        'cap': 0.11,
        'cca': 22000.0,
        'district': 'Tiruppur',
        'frl': 335.28,
        'last_pct': 72.0,
        'lat': 10.4167,
        'level': 331.0,
        'lon': 77.2667,
        'mw': 4.0,
        'name': 'Amaravathi Dam',
        'norm_pct': 68.0,
        'pct': 81.8,
        'region': 'Southern',
        'state': 'Tamil Nadu',
        'storage': 0.09,
        'warn': False},
    {   'basin': 'Kodayar Basin',
        'cap': 0.13,
        'cca': 20000.0,
        'district': 'Kanyakumari',
        'frl': 42.06,
        'last_pct': 75.0,
        'lat': 8.4333,
        'level': 39.5,
        'lon': 77.3167,
        'mw': 0.0,
        'name': 'Pechiparai Dam',
        'norm_pct': 70.0,
        'pct': 84.6,
        'region': 'Southern',
        'state': 'Tamil Nadu',
        'storage': 0.11,
        'warn': False},
    {   'basin': 'Paralayar Basin',
        'cap': 0.08,
        'cca': 15000.0,
        'district': 'Kanyakumari',
        'frl': 93.88,
        'last_pct': 78.0,
        'lat': 8.3833,
        'level': 90.2,
        'lon': 77.35,
        'mw': 0.0,
        'name': 'Perunchani Dam',
        'norm_pct': 72.0,
        'pct': 87.5,
        'region': 'Southern',
        'state': 'Tamil Nadu',
        'storage': 0.07,
        'warn': True},
    {   'basin': 'Periyar Basin',
        'cap': 1.46,
        'cca': 0.0,
        'district': 'Idukki',
        'frl': 732.43,
        'last_pct': 70.2,
        'lat': 9.85,
        'level': 718.6,
        'lon': 76.97,
        'mw': 780.0,
        'name': 'Idukki Dam (Arch Dam)',
        'norm_pct': 72.0,
        'pct': 76.7,
        'region': 'Southern',
        'state': 'Kerala',
        'storage': 1.12,
        'warn': False},
    {   'basin': 'Periyar Basin',
        'cap': 0.44,
        'cca': 81000.0,
        'district': 'Idukki',
        'frl': 43.28,
        'last_pct': 82.0,
        'lat': 9.5294,
        'level': 41.5,
        'lon': 77.1433,
        'mw': 140.0,
        'name': 'Mullaperiyar Dam',
        'norm_pct': 77.0,
        'pct': 88.6,
        'region': 'Southern',
        'state': 'Kerala',
        'storage': 0.39,
        'warn': True},
    {   'basin': 'Bharathappuzha Basin',
        'cap': 0.23,
        'cca': 42000.0,
        'district': 'Palakkad',
        'frl': 115.06,
        'last_pct': 74.0,
        'lat': 10.8333,
        'level': 112.4,
        'lon': 76.6833,
        'mw': 2.5,
        'name': 'Malampuzha Dam',
        'norm_pct': 70.0,
        'pct': 82.6,
        'region': 'Southern',
        'state': 'Kerala',
        'storage': 0.19,
        'warn': False},
    {   'basin': 'Chalakkudy Basin',
        'cap': 0.5,
        'cca': 0.0,
        'district': 'Palakkad',
        'frl': 556.26,
        'last_pct': 80.0,
        'lat': 10.3833,
        'level': 553.1,
        'lon': 76.7833,
        'mw': 185.0,
        'name': 'Parambikulam Dam',
        'norm_pct': 75.0,
        'pct': 88.0,
        'region': 'Southern',
        'state': 'Kerala',
        'storage': 0.44,
        'warn': True},
    {   'basin': 'Kabini Basin',
        'cap': 0.21,
        'cca': 0.0,
        'district': 'Wayanad',
        'frl': 775.6,
        'last_pct': 75.0,
        'lat': 11.6667,
        'level': 771.8,
        'lon': 75.95,
        'mw': 0.0,
        'name': 'Banasura Sagar Dam',
        'norm_pct': 72.0,
        'pct': 81.0,
        'region': 'Southern',
        'state': 'Kerala',
        'storage': 0.17,
        'warn': False},
    {   'basin': 'Neyyar Basin',
        'cap': 0.11,
        'cca': 15000.0,
        'district': 'Thiruvananthapuram',
        'frl': 84.73,
        'last_pct': 73.0,
        'lat': 8.5333,
        'level': 81.9,
        'lon': 77.15,
        'mw': 0.0,
        'name': 'Neyyar Dam',
        'norm_pct': 70.0,
        'pct': 81.8,
        'region': 'Southern',
        'state': 'Kerala',
        'storage': 0.09,
        'warn': False},
    {   'basin': 'Pamba Basin',
        'cap': 0.45,
        'cca': 0.0,
        'district': 'Pathanamthitta',
        'frl': 981.46,
        'last_pct': 72.0,
        'lat': 9.3167,
        'level': 974.2,
        'lon': 77.1333,
        'mw': 300.0,
        'name': 'Kakki Reservoir',
        'norm_pct': 71.0,
        'pct': 80.0,
        'region': 'Southern',
        'state': 'Kerala',
        'storage': 0.36,
        'warn': False},
    {   'basin': 'Kallada Basin',
        'cap': 0.5,
        'cca': 61000.0,
        'district': 'Kollam',
        'frl': 115.82,
        'last_pct': 76.0,
        'lat': 8.95,
        'level': 111.5,
        'lon': 77.0833,
        'mw': 15.0,
        'name': 'Kallada Dam (Parappar)',
        'norm_pct': 73.0,
        'pct': 82.0,
        'region': 'Southern',
        'state': 'Kerala',
        'storage': 0.41,
        'warn': False},
    {   'basin': 'Krishna Basin',
        'cap': 2.79,
        'cca': 0.0,
        'district': 'Satara',
        'frl': 657.91,
        'last_pct': 86.0,
        'lat': 17.4,
        'level': 655.4,
        'lon': 73.75,
        'mw': 1960.0,
        'name': 'Koyna Dam',
        'norm_pct': 80.0,
        'pct': 93.5,
        'region': 'Western',
        'state': 'Maharashtra',
        'storage': 2.61,
        'warn': True},
    {   'basin': 'Godavari Basin',
        'cap': 2.17,
        'cca': 142000.0,
        'district': 'Chhatrapati Sambhajinagar',
        'frl': 463.91,
        'last_pct': 78.0,
        'lat': 19.4833,
        'level': 461.2,
        'lon': 75.3833,
        'mw': 12.0,
        'name': 'Jayakwadi Dam (Nath Sagar)',
        'norm_pct': 74.0,
        'pct': 88.9,
        'region': 'Western',
        'state': 'Maharashtra',
        'storage': 1.93,
        'warn': True},
    {   'basin': 'Krishna Basin',
        'cap': 1.52,
        'cca': 108000.0,
        'district': 'Solapur',
        'frl': 496.83,
        'last_pct': 82.0,
        'lat': 18.0667,
        'level': 494.5,
        'lon': 75.1167,
        'mw': 12.0,
        'name': 'Ujjani Dam (Bhima)',
        'norm_pct': 77.0,
        'pct': 90.8,
        'region': 'Western',
        'state': 'Maharashtra',
        'storage': 1.38,
        'warn': True},
    {   'basin': 'Ulhas Basin',
        'cap': 0.94,
        'cca': 23000.0,
        'district': 'Thane',
        'frl': 142.07,
        'last_pct': 88.0,
        'lat': 19.5167,
        'level': 140.2,
        'lon': 73.4167,
        'mw': 15.0,
        'name': 'Bhatsa Dam',
        'norm_pct': 82.0,
        'pct': 94.7,
        'region': 'Western',
        'state': 'Maharashtra',
        'storage': 0.89,
        'warn': True},
    {   'basin': 'Tansa Basin',
        'cap': 0.18,
        'cca': 0.0,
        'district': 'Thane',
        'frl': 128.63,
        'last_pct': 91.0,
        'lat': 19.55,
        'level': 128.1,
        'lon': 73.2667,
        'mw': 0.0,
        'name': 'Tansa Dam',
        'norm_pct': 85.0,
        'pct': 94.4,
        'region': 'Western',
        'state': 'Maharashtra',
        'storage': 0.17,
        'warn': True},
    {   'basin': 'Mutha Basin',
        'cap': 0.09,
        'cca': 45000.0,
        'district': 'Pune',
        'frl': 582.47,
        'last_pct': 85.0,
        'lat': 18.4333,
        'level': 582.1,
        'lon': 73.7667,
        'mw': 0.0,
        'name': 'Khadakwasla Dam',
        'norm_pct': 80.0,
        'pct': 88.9,
        'region': 'Western',
        'state': 'Maharashtra',
        'storage': 0.08,
        'warn': True},
    {   'basin': 'Mula Basin',
        'cap': 0.57,
        'cca': 0.0,
        'district': 'Pune',
        'frl': 607.16,
        'last_pct': 86.0,
        'lat': 18.5167,
        'level': 605.2,
        'lon': 73.5167,
        'mw': 300.0,
        'name': 'Mulshi Dam',
        'norm_pct': 80.0,
        'pct': 93.0,
        'region': 'Western',
        'state': 'Maharashtra',
        'storage': 0.53,
        'warn': True},
    {   'basin': 'Godavari Basin',
        'cap': 1.09,
        'cca': 104000.0,
        'district': 'Nagpur',
        'frl': 490.0,
        'last_pct': 80.0,
        'lat': 21.5333,
        'level': 487.8,
        'lon': 79.2333,
        'mw': 160.0,
        'name': 'Totladoh Dam (Pench)',
        'norm_pct': 76.0,
        'pct': 88.1,
        'region': 'Western',
        'state': 'Maharashtra',
        'storage': 0.96,
        'warn': True},
    {   'basin': 'Krishna Basin',
        'cap': 0.78,
        'cca': 43000.0,
        'district': 'Sangli',
        'frl': 627.0,
        'last_pct': 83.0,
        'lat': 17.15,
        'level': 624.1,
        'lon': 73.9167,
        'mw': 16.0,
        'name': 'Warna Dam',
        'norm_pct': 78.0,
        'pct': 91.0,
        'region': 'Western',
        'state': 'Maharashtra',
        'storage': 0.71,
        'warn': True},
    {   'basin': 'Wainganga Basin',
        'cap': 1.15,
        'cca': 250000.0,
        'district': 'Bhandara',
        'frl': 245.5,
        'last_pct': 76.0,
        'lat': 20.8667,
        'level': 243.2,
        'lon': 79.6167,
        'mw': 24.0,
        'name': 'Ghosikhurd Dam (Indira Sagar)',
        'norm_pct': 71.0,
        'pct': 85.2,
        'region': 'Western',
        'state': 'Maharashtra',
        'storage': 0.98,
        'warn': True},
    {   'basin': 'Ambi Basin',
        'cap': 0.31,
        'cca': 0.0,
        'district': 'Pune',
        'frl': 636.42,
        'last_pct': 86.0,
        'lat': 18.3833,
        'level': 634.8,
        'lon': 73.6167,
        'mw': 0.0,
        'name': 'Panshet Dam (Tanajisagar)',
        'norm_pct': 82.0,
        'pct': 93.5,
        'region': 'Western',
        'state': 'Maharashtra',
        'storage': 0.29,
        'warn': True},
    {   'basin': 'Narmada Basin',
        'cap': 5.76,
        'cca': 1845000.0,
        'district': 'Narmada',
        'frl': 138.68,
        'last_pct': 79.5,
        'lat': 21.829,
        'level': 135.1,
        'lon': 73.7483,
        'mw': 1450.0,
        'name': 'Sardar Sarovar Dam',
        'norm_pct': 76.0,
        'pct': 84.9,
        'region': 'Western',
        'state': 'Gujarat',
        'storage': 4.89,
        'warn': False},
    {   'basin': 'Tapi Basin',
        'cap': 7.41,
        'cca': 152000.0,
        'district': 'Tapi',
        'frl': 105.16,
        'last_pct': 81.0,
        'lat': 21.25,
        'level': 103.4,
        'lon': 73.5833,
        'mw': 300.0,
        'name': 'Ukai Dam (Vallabh Sagar)',
        'norm_pct': 76.0,
        'pct': 88.3,
        'region': 'Western',
        'state': 'Gujarat',
        'storage': 6.54,
        'warn': True},
    {   'basin': 'Mahi Basin',
        'cap': 1.54,
        'cca': 19000.0,
        'district': 'Mahisagar',
        'frl': 127.71,
        'last_pct': 78.0,
        'lat': 23.3,
        'level': 125.1,
        'lon': 73.8333,
        'mw': 240.0,
        'name': 'Kadana Dam',
        'norm_pct': 74.0,
        'pct': 85.7,
        'region': 'Western',
        'state': 'Gujarat',
        'storage': 1.32,
        'warn': True},
    {   'basin': 'Sabarmati Basin',
        'cap': 0.81,
        'cca': 61000.0,
        'district': 'Mehsana',
        'frl': 189.59,
        'last_pct': 71.0,
        'lat': 24.0,
        'level': 185.2,
        'lon': 72.85,
        'mw': 0.0,
        'name': 'Dharoi Dam',
        'norm_pct': 68.0,
        'pct': 79.0,
        'region': 'Western',
        'state': 'Gujarat',
        'storage': 0.64,
        'warn': False},
    {   'basin': 'Banas Basin',
        'cap': 0.46,
        'cca': 45000.0,
        'district': 'Banaskantha',
        'frl': 184.1,
        'last_pct': 67.0,
        'lat': 24.3333,
        'level': 178.6,
        'lon': 72.3333,
        'mw': 0.0,
        'name': 'Dantiwada Dam',
        'norm_pct': 65.0,
        'pct': 73.9,
        'region': 'Western',
        'state': 'Gujarat',
        'storage': 0.34,
        'warn': False},
    {   'basin': 'Narmada Basin',
        'cap': 0.58,
        'cca': 51000.0,
        'district': 'Narmada',
        'frl': 115.25,
        'last_pct': 79.0,
        'lat': 21.8333,
        'level': 113.1,
        'lon': 73.5333,
        'mw': 0.0,
        'name': 'Karjan Dam',
        'norm_pct': 75.0,
        'pct': 87.9,
        'region': 'Western',
        'state': 'Gujarat',
        'storage': 0.51,
        'warn': True},
    {   'basin': 'Narmada Basin',
        'cap': 9.75,
        'cca': 123000.0,
        'district': 'Khandwa',
        'frl': 262.13,
        'last_pct': 83.0,
        'lat': 22.2833,
        'level': 260.4,
        'lon': 76.4667,
        'mw': 1000.0,
        'name': 'Indira Sagar Dam',
        'norm_pct': 78.0,
        'pct': 90.1,
        'region': 'Central',
        'state': 'Madhya Pradesh',
        'storage': 8.78,
        'warn': True},
    {   'basin': 'Narmada Basin',
        'cap': 0.3,
        'cca': 147000.0,
        'district': 'Khandwa',
        'frl': 196.6,
        'last_pct': 84.0,
        'lat': 22.25,
        'level': 195.2,
        'lon': 76.15,
        'mw': 520.0,
        'name': 'Omkareshwar Dam',
        'norm_pct': 80.0,
        'pct': 90.0,
        'region': 'Central',
        'state': 'Madhya Pradesh',
        'storage': 0.27,
        'warn': True},
    {   'basin': 'Narmada Basin',
        'cap': 3.18,
        'cca': 157000.0,
        'district': 'Jabalpur',
        'frl': 422.76,
        'last_pct': 82.0,
        'lat': 22.9333,
        'level': 421.2,
        'lon': 79.9167,
        'mw': 105.0,
        'name': 'Bargi Dam (Rani Avantibai)',
        'norm_pct': 77.0,
        'pct': 90.3,
        'region': 'Central',
        'state': 'Madhya Pradesh',
        'storage': 2.87,
        'warn': True},
    {   'basin': 'Chambal Basin',
        'cap': 6.83,
        'cca': 220000.0,
        'district': 'Mandsaur',
        'frl': 399.9,
        'last_pct': 79.0,
        'lat': 24.7,
        'level': 397.4,
        'lon': 75.55,
        'mw': 115.0,
        'name': 'Gandhi Sagar Dam',
        'norm_pct': 75.0,
        'pct': 86.2,
        'region': 'Central',
        'state': 'Madhya Pradesh',
        'storage': 5.89,
        'warn': True},
    {   'basin': 'Sone Basin',
        'cap': 5.41,
        'cca': 249000.0,
        'district': 'Shahdol',
        'frl': 341.64,
        'last_pct': 78.0,
        'lat': 24.1833,
        'level': 339.2,
        'lon': 81.2833,
        'mw': 425.0,
        'name': 'Bansagar Dam',
        'norm_pct': 74.0,
        'pct': 85.9,
        'region': 'Central',
        'state': 'Madhya Pradesh',
        'storage': 4.65,
        'warn': True},
    {   'basin': 'Narmada Basin',
        'cap': 1.94,
        'cca': 247000.0,
        'district': 'Narmadapuram',
        'frl': 355.4,
        'last_pct': 80.0,
        'lat': 22.55,
        'level': 353.1,
        'lon': 77.9667,
        'mw': 13.5,
        'name': 'Tawa Reservoir',
        'norm_pct': 76.0,
        'pct': 88.1,
        'region': 'Central',
        'state': 'Madhya Pradesh',
        'storage': 1.71,
        'warn': True},
    {   'basin': 'Betwa Basin',
        'cap': 1.95,
        'cca': 109000.0,
        'district': 'Ashoknagar / Lalitpur',
        'frl': 371.0,
        'last_pct': 77.0,
        'lat': 24.7667,
        'level': 368.5,
        'lon': 78.2333,
        'mw': 45.0,
        'name': 'Rajghat Dam',
        'norm_pct': 73.0,
        'pct': 86.2,
        'region': 'Central',
        'state': 'Madhya Pradesh / UP',
        'storage': 1.68,
        'warn': True},
    {   'basin': 'Mahanadi Basin',
        'cap': 5.82,
        'cca': 267000.0,
        'district': 'Sambalpur',
        'frl': 192.02,
        'last_pct': 80.1,
        'lat': 21.5276,
        'level': 190.45,
        'lon': 83.8711,
        'mw': 347.5,
        'name': 'Hirakud Reservoir',
        'norm_pct': 78.0,
        'pct': 87.9,
        'region': 'Eastern',
        'state': 'Odisha',
        'storage': 5.12,
        'warn': True},
    {   'basin': 'Brahmani Basin',
        'cap': 3.43,
        'cca': 423000.0,
        'district': 'Angul',
        'frl': 123.5,
        'last_pct': 81.0,
        'lat': 21.28,
        'level': 121.2,
        'lon': 85.03,
        'mw': 250.0,
        'name': 'Rengali Dam',
        'norm_pct': 76.0,
        'pct': 86.9,
        'region': 'Eastern',
        'state': 'Odisha',
        'storage': 2.98,
        'warn': True},
    {   'basin': 'Godavari Basin',
        'cap': 0.93,
        'cca': 44000.0,
        'district': 'Koraput',
        'frl': 858.0,
        'last_pct': 77.0,
        'lat': 18.8167,
        'level': 854.2,
        'lon': 82.6167,
        'mw': 320.0,
        'name': 'Kolab Reservoir (Upper Kolab)',
        'norm_pct': 73.0,
        'pct': 84.9,
        'region': 'Eastern',
        'state': 'Odisha',
        'storage': 0.79,
        'warn': False},
    {   'basin': 'Godavari Basin',
        'cap': 1.44,
        'cca': 109000.0,
        'district': 'Kalahandi / Nabarangpur',
        'frl': 642.0,
        'last_pct': 81.0,
        'lat': 19.2667,
        'level': 639.1,
        'lon': 82.8333,
        'mw': 600.0,
        'name': 'Indravati Dam (Upper Indravati)',
        'norm_pct': 77.0,
        'pct': 88.9,
        'region': 'Eastern',
        'state': 'Odisha',
        'storage': 1.28,
        'warn': True},
    {   'basin': 'Godavari Basin',
        'cap': 2.68,
        'cca': 0.0,
        'district': 'Malkangiri',
        'frl': 462.08,
        'last_pct': 79.0,
        'lat': 18.15,
        'level': 458.5,
        'lon': 82.1167,
        'mw': 510.0,
        'name': 'Balimela Reservoir',
        'norm_pct': 75.0,
        'pct': 85.4,
        'region': 'Eastern',
        'state': 'Odisha',
        'storage': 2.29,
        'warn': True},
    {   'basin': 'Godavari Basin',
        'cap': 0.97,
        'cca': 0.0,
        'district': 'Koraput / Alluri',
        'frl': 838.2,
        'last_pct': 79.5,
        'lat': 18.45,
        'level': 835.4,
        'lon': 82.55,
        'mw': 120.0,
        'name': 'Jalaput Dam (Machkund)',
        'norm_pct': 76.0,
        'pct': 86.6,
        'region': 'Eastern',
        'state': 'Odisha / AP',
        'storage': 0.84,
        'warn': True},
    {   'basin': 'Sone Basin',
        'cap': 8.97,
        'cca': 0.0,
        'district': 'Sonbhadra',
        'frl': 268.22,
        'last_pct': 76.0,
        'lat': 24.2,
        'level': 264.8,
        'lon': 83.0333,
        'mw': 300.0,
        'name': 'Rihand Dam (Govind Ballabh Pant)',
        'norm_pct': 72.0,
        'pct': 83.1,
        'region': 'Northern',
        'state': 'Uttar Pradesh',
        'storage': 7.45,
        'warn': False},
    {   'basin': 'Betwa Basin',
        'cap': 1.13,
        'cca': 113000.0,
        'district': 'Lalitpur',
        'frl': 308.46,
        'last_pct': 81.0,
        'lat': 25.1,
        'level': 306.9,
        'lon': 78.3833,
        'mw': 30.6,
        'name': 'Matatila Dam',
        'norm_pct': 77.0,
        'pct': 89.4,
        'region': 'Northern',
        'state': 'Uttar Pradesh',
        'storage': 1.01,
        'warn': True},
    {   'basin': 'Ganga Basin',
        'cap': 0.44,
        'cca': 140000.0,
        'district': 'Pilibhit',
        'frl': 190.5,
        'last_pct': 74.0,
        'lat': 28.5667,
        'level': 187.9,
        'lon': 80.05,
        'mw': 0.0,
        'name': 'Sharda Sagar Dam',
        'norm_pct': 70.0,
        'pct': 81.8,
        'region': 'Northern',
        'state': 'Uttar Pradesh',
        'storage': 0.36,
        'warn': False},
    {   'basin': 'Ganga Basin',
        'cap': 2.62,
        'cca': 270000.0,
        'district': 'Tehri Garhwal',
        'frl': 830.0,
        'last_pct': 72.0,
        'lat': 30.378,
        'level': 812.5,
        'lon': 78.48,
        'mw': 2400.0,
        'name': 'Tehri Dam (Highest in India)',
        'norm_pct': 74.0,
        'pct': 78.2,
        'region': 'Northern',
        'state': 'Uttarakhand',
        'storage': 2.05,
        'warn': False},
    {   'basin': 'Ganga Basin',
        'cap': 2.19,
        'cca': 575000.0,
        'district': 'Pauri Garhwal',
        'frl': 365.3,
        'last_pct': 73.0,
        'lat': 29.5167,
        'level': 358.4,
        'lon': 78.75,
        'mw': 198.0,
        'name': 'Ramganga Dam (Kalagarh)',
        'norm_pct': 71.0,
        'pct': 79.5,
        'region': 'Northern',
        'state': 'Uttarakhand',
        'storage': 1.74,
        'warn': False},
    {   'basin': 'Ganga Basin',
        'cap': 0.09,
        'cca': 0.0,
        'district': 'Tehri Garhwal',
        'frl': 612.5,
        'last_pct': 74.0,
        'lat': 30.2833,
        'level': 608.2,
        'lon': 78.5,
        'mw': 400.0,
        'name': 'Koteshwar Dam',
        'norm_pct': 72.0,
        'pct': 77.8,
        'region': 'Northern',
        'state': 'Uttarakhand',
        'storage': 0.07,
        'warn': False},
    {   'basin': 'Indus / Sutlej',
        'cap': 6.23,
        'cca': 1350000.0,
        'district': 'Bilaspur',
        'frl': 515.11,
        'last_pct': 73.1,
        'lat': 31.4116,
        'level': 502.8,
        'lon': 76.4369,
        'mw': 1325.0,
        'name': 'Bhakra Dam',
        'norm_pct': 75.0,
        'pct': 78.3,
        'region': 'Northern',
        'state': 'Himachal Pradesh',
        'storage': 4.88,
        'warn': False},
    {   'basin': 'Indus / Beas',
        'cap': 6.16,
        'cca': 160000.0,
        'district': 'Kangra',
        'frl': 426.72,
        'last_pct': 75.0,
        'lat': 31.9667,
        'level': 420.1,
        'lon': 75.95,
        'mw': 396.0,
        'name': 'Pong Dam (Maharana Pratap)',
        'norm_pct': 73.0,
        'pct': 81.5,
        'region': 'Northern',
        'state': 'Himachal Pradesh',
        'storage': 5.02,
        'warn': False},
    {   'basin': 'Indus / Sutlej',
        'cap': 0.56,
        'cca': 0.0,
        'district': 'Bilaspur',
        'frl': 642.0,
        'last_pct': 85.0,
        'lat': 31.3667,
        'level': 639.5,
        'lon': 76.8667,
        'mw': 800.0,
        'name': 'Kol Dam',
        'norm_pct': 80.0,
        'pct': 91.1,
        'region': 'Northern',
        'state': 'Himachal Pradesh',
        'storage': 0.51,
        'warn': True},
    {   'basin': 'Indus / Ravi',
        'cap': 0.39,
        'cca': 0.0,
        'district': 'Chamba',
        'frl': 760.0,
        'last_pct': 78.0,
        'lat': 32.5833,
        'level': 754.2,
        'lon': 75.9833,
        'mw': 540.0,
        'name': 'Chamera Dam I',
        'norm_pct': 75.0,
        'pct': 84.6,
        'region': 'Northern',
        'state': 'Himachal Pradesh',
        'storage': 0.33,
        'warn': False},
    {   'basin': 'Indus / Ravi',
        'cap': 2.34,
        'cca': 348000.0,
        'district': 'Pathankot',
        'frl': 527.91,
        'last_pct': 74.0,
        'lat': 32.4333,
        'level': 518.5,
        'lon': 75.7333,
        'mw': 600.0,
        'name': 'Ranjit Sagar Dam (Thein Dam)',
        'norm_pct': 72.0,
        'pct': 80.8,
        'region': 'Northern',
        'state': 'Punjab',
        'storage': 1.89,
        'warn': False},
    {   'basin': 'Chambal Basin',
        'cap': 1.44,
        'cca': 120000.0,
        'district': 'Rawatbhata',
        'frl': 352.81,
        'last_pct': 79.0,
        'lat': 24.9333,
        'level': 350.2,
        'lon': 75.5833,
        'mw': 172.0,
        'name': 'Rana Pratap Sagar',
        'norm_pct': 75.0,
        'pct': 86.8,
        'region': 'Northern',
        'state': 'Rajasthan',
        'storage': 1.25,
        'warn': True},
    {   'basin': 'Chambal Basin',
        'cap': 0.07,
        'cca': 0.0,
        'district': 'Kota',
        'frl': 298.7,
        'last_pct': 80.0,
        'lat': 25.05,
        'level': 297.1,
        'lon': 75.6833,
        'mw': 99.0,
        'name': 'Jawahar Sagar Dam',
        'norm_pct': 78.0,
        'pct': 85.7,
        'region': 'Northern',
        'state': 'Rajasthan',
        'storage': 0.06,
        'warn': True},
    {   'basin': 'Chambal Basin',
        'cap': 0.1,
        'cca': 229000.0,
        'district': 'Kota',
        'frl': 260.3,
        'last_pct': 85.0,
        'lat': 25.1833,
        'level': 259.8,
        'lon': 75.8333,
        'mw': 0.0,
        'name': 'Kota Barrage',
        'norm_pct': 82.0,
        'pct': 90.0,
        'region': 'Northern',
        'state': 'Rajasthan',
        'storage': 0.09,
        'warn': True},
    {   'basin': 'Banas Basin',
        'cap': 1.1,
        'cca': 81000.0,
        'district': 'Tonk',
        'frl': 315.5,
        'last_pct': 81.0,
        'lat': 26.0167,
        'level': 313.8,
        'lon': 75.4,
        'mw': 0.0,
        'name': 'Bisalpur Dam',
        'norm_pct': 76.0,
        'pct': 89.1,
        'region': 'Northern',
        'state': 'Rajasthan',
        'storage': 0.98,
        'warn': True},
    {   'basin': 'Mahi Basin',
        'cap': 2.06,
        'cca': 80000.0,
        'district': 'Banswara',
        'frl': 281.5,
        'last_pct': 80.0,
        'lat': 23.6333,
        'level': 279.1,
        'lon': 74.55,
        'mw': 140.0,
        'name': 'Mahi Bajaj Sagar',
        'norm_pct': 75.0,
        'pct': 88.8,
        'region': 'Northern',
        'state': 'Rajasthan',
        'storage': 1.83,
        'warn': True},
    {   'basin': 'Damodar (Barakar)',
        'cap': 0.61,
        'cca': 50000.0,
        'district': 'Dhanbad',
        'frl': 150.88,
        'last_pct': 77.0,
        'lat': 23.7833,
        'level': 147.2,
        'lon': 86.8167,
        'mw': 60.0,
        'name': 'Maithon Dam',
        'norm_pct': 73.0,
        'pct': 83.6,
        'region': 'Eastern',
        'state': 'Jharkhand',
        'storage': 0.51,
        'warn': False},
    {   'basin': 'Damodar Basin',
        'cap': 0.34,
        'cca': 230000.0,
        'district': 'Dhanbad',
        'frl': 135.64,
        'last_pct': 75.0,
        'lat': 23.6833,
        'level': 131.8,
        'lon': 86.75,
        'mw': 80.0,
        'name': 'Panchet Dam',
        'norm_pct': 71.0,
        'pct': 82.4,
        'region': 'Eastern',
        'state': 'Jharkhand',
        'storage': 0.28,
        'warn': False},
    {   'basin': 'Damodar (Barakar)',
        'cap': 0.18,
        'cca': 40000.0,
        'district': 'Koderma',
        'frl': 371.86,
        'last_pct': 76.0,
        'lat': 24.3167,
        'level': 368.1,
        'lon': 85.5333,
        'mw': 4.0,
        'name': 'Tilaiya Dam',
        'norm_pct': 72.0,
        'pct': 83.3,
        'region': 'Eastern',
        'state': 'Jharkhand',
        'storage': 0.15,
        'warn': False},
    {   'basin': 'Damodar (Konar)',
        'cap': 0.22,
        'cca': 26000.0,
        'district': 'Hazaribagh',
        'frl': 429.77,
        'last_pct': 74.0,
        'lat': 23.9167,
        'level': 425.4,
        'lon': 85.7667,
        'mw': 0.0,
        'name': 'Konar Dam',
        'norm_pct': 70.0,
        'pct': 81.8,
        'region': 'Eastern',
        'state': 'Jharkhand',
        'storage': 0.18,
        'warn': False},
    {   'basin': 'Damodar Basin',
        'cap': 0.82,
        'cca': 0.0,
        'district': 'Bokaro',
        'frl': 269.44,
        'last_pct': 76.0,
        'lat': 23.7333,
        'level': 265.1,
        'lon': 85.8333,
        'mw': 0.0,
        'name': 'Tenughat Dam',
        'norm_pct': 73.0,
        'pct': 84.1,
        'region': 'Eastern',
        'state': 'Jharkhand',
        'storage': 0.69,
        'warn': False},
    {   'basin': 'Sone Basin',
        'cap': 0.95,
        'cca': 111000.0,
        'district': 'Latehar',
        'frl': 367.28,
        'last_pct': 68.0,
        'lat': 23.85,
        'level': 359.8,
        'lon': 84.05,
        'mw': 24.0,
        'name': 'North Koel Dam (Mandal Dam)',
        'norm_pct': 65.0,
        'pct': 75.8,
        'region': 'Eastern',
        'state': 'Jharkhand',
        'storage': 0.72,
        'warn': False},
    {   'basin': 'Ganga Basin',
        'cap': 0.11,
        'cca': 45000.0,
        'district': 'Banka',
        'frl': 132.59,
        'last_pct': 65.0,
        'lat': 24.8833,
        'level': 128.4,
        'lon': 86.65,
        'mw': 0.0,
        'name': 'Badua Dam',
        'norm_pct': 68.0,
        'pct': 72.7,
        'region': 'Eastern',
        'state': 'Bihar',
        'storage': 0.08,
        'warn': False},
    {   'basin': 'Ganga Basin',
        'cap': 0.16,
        'cca': 62000.0,
        'district': 'Banka',
        'frl': 158.5,
        'last_pct': 68.0,
        'lat': 24.7833,
        'level': 153.2,
        'lon': 86.9167,
        'mw': 0.0,
        'name': 'Chandan Dam',
        'norm_pct': 69.0,
        'pct': 75.0,
        'region': 'Eastern',
        'state': 'Bihar',
        'storage': 0.12,
        'warn': False},
    {   'basin': 'Kangsabati Basin',
        'cap': 1.04,
        'cca': 340000.0,
        'district': 'Bankura',
        'frl': 134.11,
        'last_pct': 76.0,
        'lat': 22.9667,
        'level': 130.8,
        'lon': 86.7833,
        'mw': 0.0,
        'name': 'Mukutmanipur Dam (Kangsabati)',
        'norm_pct': 72.0,
        'pct': 82.7,
        'region': 'Eastern',
        'state': 'West Bengal',
        'storage': 0.86,
        'warn': False},
    {   'basin': 'Damodar Basin',
        'cap': 0.04,
        'cca': 380000.0,
        'district': 'Paschim Bardhaman',
        'frl': 64.47,
        'last_pct': 92.0,
        'lat': 23.4833,
        'level': 64.0,
        'lon': 87.3,
        'mw': 0.0,
        'name': 'Durgapur Barrage',
        'norm_pct': 88.0,
        'pct': 100.0,
        'region': 'Eastern',
        'state': 'West Bengal',
        'storage': 0.04,
        'warn': True},
    {   'basin': 'Ganga Basin',
        'cap': 0.08,
        'cca': 0.0,
        'district': 'Murshidabad',
        'frl': 22.0,
        'last_pct': 85.0,
        'lat': 24.8058,
        'level': 21.8,
        'lon': 87.9189,
        'mw': 0.0,
        'name': 'Farakka Barrage',
        'norm_pct': 80.0,
        'pct': 87.5,
        'region': 'Eastern',
        'state': 'West Bengal',
        'storage': 0.07,
        'warn': True},
    {   'basin': 'Brahmaputra / Teesta',
        'cap': 0.06,
        'cca': 922000.0,
        'district': 'Jalpaiguri',
        'frl': 114.5,
        'last_pct': 80.0,
        'lat': 26.75,
        'level': 113.8,
        'lon': 88.5833,
        'mw': 67.5,
        'name': 'Teesta Barrage',
        'norm_pct': 78.0,
        'pct': 83.3,
        'region': 'Eastern',
        'state': 'West Bengal',
        'storage': 0.05,
        'warn': False},
    {   'basin': 'Mahanadi Basin',
        'cap': 2.89,
        'cca': 247000.0,
        'district': 'Korba',
        'frl': 359.66,
        'last_pct': 81.0,
        'lat': 22.6167,
        'level': 357.2,
        'lon': 82.5833,
        'mw': 120.0,
        'name': 'Hasdeo Bango Dam (Minimata)',
        'norm_pct': 76.0,
        'pct': 89.3,
        'region': 'Central',
        'state': 'Chhattisgarh',
        'storage': 2.58,
        'warn': True},
    {   'basin': 'Mahanadi Basin',
        'cap': 0.91,
        'cca': 298000.0,
        'district': 'Dhamtari',
        'frl': 348.7,
        'last_pct': 80.0,
        'lat': 20.6167,
        'level': 346.4,
        'lon': 81.5667,
        'mw': 10.0,
        'name': 'Ravishankar Sagar (Gangrel)',
        'norm_pct': 75.0,
        'pct': 89.0,
        'region': 'Central',
        'state': 'Chhattisgarh',
        'storage': 0.81,
        'warn': True},
    {   'basin': 'Mahanadi Basin',
        'cap': 0.31,
        'cca': 113000.0,
        'district': 'Balod',
        'frl': 332.23,
        'last_pct': 76.0,
        'lat': 20.7833,
        'level': 329.8,
        'lon': 81.2333,
        'mw': 0.0,
        'name': 'Tandula Dam',
        'norm_pct': 72.0,
        'pct': 83.9,
        'region': 'Central',
        'state': 'Chhattisgarh',
        'storage': 0.26,
        'warn': False},
    {   'basin': 'Mahanadi Basin',
        'cap': 0.16,
        'cca': 45000.0,
        'district': 'Dhamtari',
        'frl': 355.09,
        'last_pct': 74.0,
        'lat': 20.5333,
        'level': 352.4,
        'lon': 81.65,
        'mw': 0.0,
        'name': 'Mahanadi Reservoir Project (Murrum Silli)',
        'norm_pct': 70.0,
        'pct': 81.3,
        'region': 'Central',
        'state': 'Chhattisgarh',
        'storage': 0.13,
        'warn': False},
    {   'basin': 'Brahmaputra Basin',
        'cap': 1.37,
        'cca': 0.0,
        'district': 'Dhemaji / Lower Subansiri',
        'frl': 205.0,
        'last_pct': 70.0,
        'lat': 27.55,
        'level': 196.5,
        'lon': 94.2667,
        'mw': 2000.0,
        'name': 'Subansiri Lower Dam',
        'norm_pct': 72.0,
        'pct': 76.6,
        'region': 'Eastern',
        'state': 'Assam / Arunachal',
        'storage': 1.05,
        'warn': False},
    {   'basin': 'Brahmaputra Basin',
        'cap': 0.21,
        'cca': 0.0,
        'district': 'Lower Subansiri',
        'frl': 567.0,
        'last_pct': 78.0,
        'lat': 27.3333,
        'level': 562.4,
        'lon': 93.75,
        'mw': 405.0,
        'name': 'Ranganadi Dam (Yazali)',
        'norm_pct': 75.0,
        'pct': 85.7,
        'region': 'Eastern',
        'state': 'Arunachal Pradesh',
        'storage': 0.18,
        'warn': True},
    {   'basin': 'Brahmaputra Basin',
        'cap': 0.15,
        'cca': 0.0,
        'district': 'Ri-Bhoi',
        'frl': 978.41,
        'last_pct': 74.0,
        'lat': 25.65,
        'level': 973.5,
        'lon': 91.9,
        'mw': 185.0,
        'name': 'Umiam Dam (Barapani)',
        'norm_pct': 72.0,
        'pct': 80.0,
        'region': 'Eastern',
        'state': 'Meghalaya',
        'storage': 0.12,
        'warn': False},
    {   'basin': 'Brahmaputra Basin',
        'cap': 0.17,
        'cca': 0.0,
        'district': 'West Jaintia / Dima Hasao',
        'frl': 719.3,
        'last_pct': 75.0,
        'lat': 25.6833,
        'level': 715.1,
        'lon': 92.7667,
        'mw': 275.0,
        'name': 'Khandong Dam (Kopili)',
        'norm_pct': 73.0,
        'pct': 82.4,
        'region': 'Eastern',
        'state': 'Meghalaya / Assam',
        'storage': 0.14,
        'warn': False},
    {   'basin': 'Manipur / Chindwin',
        'cap': 0.51,
        'cca': 40000.0,
        'district': 'Bishnupur',
        'frl': 768.5,
        'last_pct': 80.0,
        'lat': 24.4333,
        'level': 767.2,
        'lon': 93.8167,
        'mw': 105.0,
        'name': 'Loktak Hydroelectric Project (Ithai)',
        'norm_pct': 76.0,
        'pct': 88.2,
        'region': 'Eastern',
        'state': 'Manipur',
        'storage': 0.45,
        'warn': True},
    {   'basin': 'Barak Basin',
        'cap': 3.8,
        'cca': 0.0,
        'district': 'Churachandpur',
        'frl': 175.0,
        'last_pct': 65.0,
        'lat': 24.2333,
        'level': 162.0,
        'lon': 93.0333,
        'mw': 1500.0,
        'name': 'Tipaimukh Dam (Proposed/Headworks)',
        'norm_pct': 68.0,
        'pct': 69.7,
        'region': 'Eastern',
        'state': 'Manipur',
        'storage': 2.65,
        'warn': False},
    {   'basin': 'Barak Basin',
        'cap': 0.18,
        'cca': 0.0,
        'district': 'Kolasib',
        'frl': 97.0,
        'last_pct': 70.0,
        'lat': 24.3667,
        'level': 92.4,
        'lon': 92.8333,
        'mw': 60.0,
        'name': 'Tuirial Dam',
        'norm_pct': 70.0,
        'pct': 77.8,
        'region': 'Eastern',
        'state': 'Mizoram',
        'storage': 0.14,
        'warn': False},
    {   'basin': 'Brahmaputra Basin',
        'cap': 0.37,
        'cca': 0.0,
        'district': 'Wokha',
        'frl': 333.0,
        'last_pct': 76.0,
        'lat': 26.2,
        'level': 328.6,
        'lon': 94.2833,
        'mw': 75.0,
        'name': 'Doyang Hydro Dam',
        'norm_pct': 72.0,
        'pct': 83.8,
        'region': 'Eastern',
        'state': 'Nagaland',
        'storage': 0.31,
        'warn': False},
    {   'basin': 'Meghna Basin',
        'cap': 0.23,
        'cca': 0.0,
        'district': 'Gomati',
        'frl': 93.57,
        'last_pct': 81.0,
        'lat': 23.4667,
        'level': 92.1,
        'lon': 91.8167,
        'mw': 15.0,
        'name': 'Gumti Dam (Dumboor)',
        'norm_pct': 76.0,
        'pct': 87.0,
        'region': 'Eastern',
        'state': 'Tripura',
        'storage': 0.2,
        'warn': True},
    {   'basin': 'Brahmaputra / Teesta',
        'cap': 0.13,
        'cca': 0.0,
        'district': 'East Sikkim',
        'frl': 579.0,
        'last_pct': 79.0,
        'lat': 27.2833,
        'level': 574.5,
        'lon': 88.5,
        'mw': 510.0,
        'name': 'Teesta-V Dam',
        'norm_pct': 75.0,
        'pct': 84.6,
        'region': 'Eastern',
        'state': 'Sikkim',
        'storage': 0.11,
        'warn': False},
    {   'basin': 'Brahmaputra / Teesta',
        'cap': 0.05,
        'cca': 0.0,
        'district': 'South Sikkim',
        'frl': 639.0,
        'last_pct': 75.0,
        'lat': 27.3,
        'level': 635.8,
        'lon': 88.2833,
        'mw': 60.0,
        'name': 'Rangit Dam (Rangit Stage III)',
        'norm_pct': 73.0,
        'pct': 80.0,
        'region': 'Eastern',
        'state': 'Sikkim',
        'storage': 0.04,
        'warn': False},
    {   'basin': 'Indus / Chenab',
        'cap': 0.4,
        'cca': 0.0,
        'district': 'Ramban',
        'frl': 840.0,
        'last_pct': 81.0,
        'lat': 33.1667,
        'level': 836.5,
        'lon': 75.3167,
        'mw': 900.0,
        'name': 'Baglihar Dam',
        'norm_pct': 78.0,
        'pct': 87.5,
        'region': 'Northern',
        'state': 'Jammu & Kashmir',
        'storage': 0.35,
        'warn': True},
    {   'basin': 'Indus / Chenab',
        'cap': 0.28,
        'cca': 0.0,
        'district': 'Reasi',
        'frl': 487.68,
        'last_pct': 76.0,
        'lat': 33.1333,
        'level': 483.2,
        'lon': 74.8333,
        'mw': 690.0,
        'name': 'Salal Dam',
        'norm_pct': 74.0,
        'pct': 82.1,
        'region': 'Northern',
        'state': 'Jammu & Kashmir',
        'storage': 0.23,
        'warn': False},
    {   'basin': 'Indus / Jhelum',
        'cap': 0.15,
        'cca': 0.0,
        'district': 'Baramulla',
        'frl': 1145.0,
        'last_pct': 75.0,
        'lat': 34.0833,
        'level': 1141.2,
        'lon': 74.0333,
        'mw': 720.0,
        'name': 'Uri Dam (Uri-I & II)',
        'norm_pct': 72.0,
        'pct': 80.0,
        'region': 'Northern',
        'state': 'Jammu & Kashmir',
        'storage': 0.12,
        'warn': False},
    {   'basin': 'Indus / Chenab',
        'cap': 0.12,
        'cca': 0.0,
        'district': 'Kishtwar',
        'frl': 1258.0,
        'last_pct': 78.0,
        'lat': 33.3167,
        'level': 1254.1,
        'lon': 75.7667,
        'mw': 390.0,
        'name': 'Dulhasti Dam',
        'norm_pct': 75.0,
        'pct': 83.3,
        'region': 'Northern',
        'state': 'Jammu & Kashmir',
        'storage': 0.1,
        'warn': False},
    {   'basin': 'Indus / Jhelum',
        'cap': 0.08,
        'cca': 0.0,
        'district': 'Bandipora',
        'frl': 2390.0,
        'last_pct': 80.0,
        'lat': 34.65,
        'level': 2386.4,
        'lon': 74.75,
        'mw': 330.0,
        'name': 'Kishanganga Dam',
        'norm_pct': 76.0,
        'pct': 87.5,
        'region': 'Northern',
        'state': 'Jammu & Kashmir',
        'storage': 0.07,
        'warn': True},
    {   'basin': 'Zuari Basin',
        'cap': 0.23,
        'cca': 14000.0,
        'district': 'South Goa',
        'frl': 42.67,
        'last_pct': 84.0,
        'lat': 15.2167,
        'level': 41.8,
        'lon': 74.1833,
        'mw': 0.0,
        'name': 'Salaulim Dam',
        'norm_pct': 80.0,
        'pct': 91.3,
        'region': 'Western',
        'state': 'Goa',
        'storage': 0.21,
        'warn': True},
    {   'basin': 'Mandovi Basin',
        'cap': 0.05,
        'cca': 5000.0,
        'district': 'North Goa',
        'frl': 93.2,
        'last_pct': 75.0,
        'lat': 15.6167,
        'level': 91.4,
        'lon': 74.1167,
        'mw': 0.0,
        'name': 'Anjunem Dam',
        'norm_pct': 72.0,
        'pct': 80.0,
        'region': 'Western',
        'state': 'Goa',
        'storage': 0.04,
        'warn': False}]

router = APIRouter(
    prefix="/dams",
    tags=["Dam / Reservoir Intelligence"],
)

@router.post("/ingest")
async def ingest_dams(
    file: UploadFile = File(...),
    db: Session = Depends(get_db),
):

    filename = (
        file.filename
        or ""
    ).lower()

    if not filename.endswith(
        ".pdf"
    ):

        raise HTTPException(
            status_code=400,
            detail=(
                "Please upload an official "
                "CWC Reservoir Storage Bulletin PDF."
            ),
        )

    content = await file.read()

    if not content:

        raise HTTPException(
            status_code=400,
            detail="Uploaded file is empty.",
        )

    temp_path = None

    try:

        with NamedTemporaryFile(
            suffix=".pdf",
            delete=False,
        ) as temp:

            temp.write(
                content
            )

            temp_path = Path(
                temp.name
            )

        return ingest_cwc_pdf(
            db=db,
            pdf_path=temp_path,
        )

    except ValueError as exc:

        raise HTTPException(
            status_code=400,
            detail=str(exc),
        )

    finally:

        if (
            temp_path is not None
            and temp_path.exists()
        ):

            temp_path.unlink()


@router.get("")
def list_dams(
    state: str | None = Query(
        None,
        min_length=2,
        max_length=100,
    ),

    limit: int = Query(
        50,
        ge=1,
        le=500,
    ),

    db: Session = Depends(get_db),
):

    query = db.query(
        Reservoir
    )

    if state:

        query = query.filter(
            Reservoir.state.ilike(
                f"%{state}%"
            )
        )

    reservoirs = (
        query
        .order_by(
            Reservoir.reservoir_name
        )
        .limit(limit)
        .all()
    )

    if not reservoirs:
        fallback = DEFAULT_RESERVOIRS
        if state:
            s = state.lower()
            fallback = [r for r in fallback if s in r["state"].lower()]
        fallback = fallback[:limit]
        return {
            "status": "success",
            "count": len(fallback),
            "source": "CWC",
            "source_type": "OFFICIAL_DATA",
            "reservoirs": fallback,
        }

    return {
        "status":
            "success",

        "count":
            len(reservoirs),

        "source":
            "CWC",

        "source_type":
            "OFFICIAL_DATA",

        "reservoirs": [
            {
                "id":
                    item.id,

                "name":
                    item.reservoir_name,

                "state":
                    item.state,

                "region":
                    item.region,

                "district":
                    item.district,

                "basin":
                    item.basin,

                "latitude":
                    item.latitude,

                "longitude":
                    item.longitude,

                "frl_m":
                    item.frl_m,

                "current_level_m":
                    item.current_level_m,

                "live_capacity_bcm":
                    item.live_capacity_bcm,

                "live_storage_bcm":
                    item.live_storage_bcm,

                "storage_percent":
                    item.storage_percent,

                "last_year_storage_percent":
                    item.last_year_storage_percent,

                "normal_storage_percent":
                    item.normal_storage_percent,

                "irrigation_cca":
                    item.irrigation_cca,

                "hydel_mw":
                    item.hydel_mw,

                "observation_date":
                    (
                        item.observation_date.isoformat()
                        if item.observation_date
                        else None
                    ),

                "source":
                    item.source,

                "source_type":
                    item.source_type,

                "official_warning": (
                    item.storage_percent is not None and item.storage_percent >= 80.0
                ),
            }

            for item in reservoirs
        ],
    }


@router.get("/nearby")
def nearby_dams(
    latitude: float = Query(
        ...,
        ge=-90,
        le=90,
    ),

    longitude: float = Query(
        ...,
        ge=-180,
        le=180,
    ),

    radius_km: float = Query(
        150,
        gt=0,
        le=1000,
    ),

    limit: int = Query(
        20,
        ge=1,
        le=100,
    ),

    db: Session = Depends(get_db),
):

    reservoirs = (
        db.query(Reservoir)
        .filter(
            Reservoir.latitude.is_not(None),
            Reservoir.longitude.is_not(None),
        )
        .all()
    )

    if not reservoirs:
        import math
        matched = []
        for d in DEFAULT_RESERVOIRS:
            dlat = d.get("latitude")
            dlon = d.get("longitude")
            if dlat is not None and dlon is not None:
                dist = 111.0 * math.sqrt((dlat - latitude)**2 + ((dlon - longitude) * math.cos(math.radians(latitude)))**2)
                if dist <= radius_km:
                    d_copy = dict(d)
                    d_copy["distance_km"] = round(dist, 1)
                    matched.append(d_copy)
        matched.sort(key=lambda x: x.get("distance_km", 9999))
        return {
            "status": "success",
            "count": len(matched[:limit]),
            "radius_km": radius_km,
            "source": "CWC",
            "source_type": "OFFICIAL_DATA",
            "reservoirs": matched[:limit],
        }

    return {
        "status":
            "success",

        "count":
            0,

        "radius_km":
            radius_km,

        "source":
            "CWC",

        "source_type":
            "OFFICIAL_DATA",

        "reservoirs":
            [],
        
        "message": (
            "The current CWC bulletin does not "
            "contain reservoir coordinates, so "
            "nearby matching is unavailable until "
            "an authoritative coordinate dataset "
            "is linked."
        ),
    }
